name = "Priyam Panchal"
rol = "Aspiring Embedded Software Developer"
email = "priyam.panchal.65@gmail.com"
phone = "+1 (***) ***-****"
birthday = "******** *, 19**"
location = "Ottawa, Ontario, Canada"
avatar = "./config/assets/avatars/my-avatar.png"
username = "richardhanrick" # <-- github user name
googlemaps = "https://maps.googleapis.com/maps/api/js?key=AIzaSyDnTSpmL5q5GVxr-0K3I7Kr5XEv2O9p-S4&callback=console.debug&libraries=maps,marker&v=beta" 
presentation = """
A self-driven, low-level development enthusiast with a rich background in Embedded Systems with ARM, STM32, ESP32, Atmel and mechatronics and C++, Python, Robotics and Automation projects, aiming for an Embedded Software Engineering role delivering innovative solutions with initiative and focus, with a results-driven approach.
"""
